# Generated by Django 2.2.13 on 2021-07-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discout_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discout_price',
            new_name='discount_price',
        ),
    ]
